// Textes et libellés Slash Studio / Bot Observatory

import { type UiText, uiText } from "@/features/workspace/core";

export const slashStudioText = {
  fr: {
    textPrefixCommand: "Commande à préfixe texte",
    everyone: "Tout le monde",
    syncing: "sync…",
    synced: "Discord OK",
    error: "erreur",
    local: "local",
    commandComposer: "Compositeur de commande",
    overview: "Vue d’ensemble",
    test: "Tester",
    disable: "Désactiver",
    export: "Export",
    type: "Type",
    state: "Statut",
    enabled: "Activée",
    scope: "Portée",
    bot: "Bot",
    guild: "Serveur",
    activeBot: "Bot actif",
    allGuilds: "Toutes les guilds",
    lastLocalSave: "Dernière sauvegarde locale",
    lastDiscordSync: "Dernière sync Discord",
    notSyncedYet: "Pas encore synchronisée",
    lastError: "Dernière erreur",
    noError: "Aucune erreur",
    previous: "Précédent",
    next: "Continuer",
    openFullEditor: "Ouvrir l’éditeur complet",
    commandCreation: "Création de commande",
    applyChanges: "Appliquer les modifications à Discord",
    createAndApply: "Créer et appliquer à Discord",
    prefixAria: "Préfixe texte",
    slashTypeHelp: "Commande / avec arguments et autocomplete.",
    userTypeHelp: "Action contextuelle sur un utilisateur.",
    messageTypeHelp: "Action contextuelle sur un message.",
    noDiscordArguments: "Ce type de commande ne prend pas d’arguments Discord.",
    commandTypes: {
      chat_input: "Commande slash",
      user: "Commande utilisateur",
      message: "Commande message",
      unknown: "Inconnu",
    },
  },
  en: {
    textPrefixCommand: "Text prefix command",
    everyone: "Everyone",
    syncing: "sync…",
    synced: "Discord OK",
    error: "error",
    local: "local",
    commandComposer: "Command Composer",
    overview: "Overview",
    test: "Test",
    disable: "Disable",
    export: "Export",
    type: "Type",
    state: "Status",
    enabled: "Enabled",
    scope: "Scope",
    bot: "Bot",
    guild: "Guild",
    activeBot: "Active bot",
    allGuilds: "All guilds",
    lastLocalSave: "Last local save",
    lastDiscordSync: "Last Discord sync",
    notSyncedYet: "Not synced yet",
    lastError: "Last error",
    noError: "No error",
    previous: "Previous",
    next: "Continue",
    openFullEditor: "Open full editor",
    commandCreation: "Command creation",
    applyChanges: "Apply changes to Discord",
    createAndApply: "Create and apply to Discord",
    prefixAria: "Text prefix",
    slashTypeHelp: "Slash command with arguments and autocomplete.",
    userTypeHelp: "Context action on a user.",
    messageTypeHelp: "Context action on a message.",
    noDiscordArguments: "This command type does not take Discord arguments.",
    commandTypes: {
      chat_input: "Slash command",
      user: "User command",
      message: "Message command",
      unknown: "Unknown",
    },
  },
} as const;

export const botOpsText = {
  fr: {
    unknown: "Inconnu",
    noActivity: "Aucune activité",
    offline: "Hors ligne",
    needsCheck: "À vérifier",
    operational: "Opérationnel",
    status: "État",
    online: "En ligne",
    bot: "Bot",
    gateway: "Gateway",
    eventCount: (count: number) => `${count} événement(s)`,
    stable: "Stable",
    uptime: "Uptime",
    localSession: "Session locale",
    servers: "Serveurs",
    textChannels: (count: number) => `${count} salons texte`,
    commands: "Commandes",
    commandsDetail: (global: number, guild: number) =>
      `${global} globales, ${guild} serveur`,
    alerts: "Alertes",
    toHandle: "À traiter",
    none: "Aucune",
    botOfflineTitle: "Bot non connecté",
    botOfflineShort: "Le bot ne reçoit pas les événements Discord.",
    currentState: (state: string) => `État actuel: ${state}.`,
    botOfflineFix: "Relance la connexion et vérifie le token.",
    lastBotErrorTitle: "Dernière erreur bot",
    lastBotErrorWhy: "Une action Discord.js ou Botdeck a échoué récemment.",
    lastBotErrorFix:
      "Ouvre le log lié puis corrige la permission ou le payload.",
    lastErrorEvidence: "lastError présent",
    limitedPermissionsTitle: "Permissions limitées",
    limitedPermissionsShort: (count: number) => `${count} salon(s) à vérifier.`,
    limitedPermissionsWhy:
      "Le rôle du bot ou une permission de salon bloque une réponse.",
    limitedPermissionsFix:
      "Vérifie Voir le salon, Envoyer des messages, Embed Links et Use Application Commands.",
    payloadTitle: "Payload refusé",
    payloadShort:
      "Discord a rejeté une commande, un embed, un modal ou un identifiant.",
    payloadWhy: "Un champ est trop long, absent ou invalide.",
    payloadFix: "Lis le détail du log et corrige le champ indiqué.",
    expiredTitle: "Interaction expirée",
    expiredShort:
      "Une commande, un bouton ou un modal a répondu trop tard ou deux fois.",
    expiredWhy:
      "Discord attend une réponse rapide et une seule réponse initiale.",
    expiredFix:
      "Réponds ou defer rapidement, puis garde les boutons expirés propres.",
    rateLimitTitle: "Rate limit",
    rateLimitShort: "Discord a limité une route API.",
    rateLimitWhy: "Trop d'appels ont été faits trop vite.",
    rateLimitFix: "Évite les rafales et laisse Discord.js gérer le retry.",
    authTitle: "Auth ou token",
    authShort: "Un log mentionne token, 401, 403 ou unauthorized.",
    authWhy: "Le token peut être invalide ou une permission globale refusée.",
    authFix: "Reconnecte le bot et ne partage jamais les logs sensibles.",
    partialCommandsTitle: "Commandes incomplètes",
    partialCommandsWhy:
      "Discord n'a pas renvoyé toutes les commandes attendues.",
    partialCommandsFix:
      "Ouvre Slash Studio et synchronise avec Discord si nécessaire.",
    partialCommandsEvidence: "partialError Slash Studio",
    allCleanTitle: "Tout est propre",
    allCleanShort: "Aucun blocage important détecté.",
    allCleanWhy:
      "La gateway est connectée et les logs récents ne montrent pas d'erreur critique.",
    allCleanFix:
      "Continue les tests. Les prochains événements apparaîtront dans le journal.",
    recentLogEvidence: (count: number) => `${count} log(s) récents`,
    logEvidence: (count: number) => `${count} log(s)`,
    permissionEvidence: (logs: number, channels: number) =>
      `${logs} log(s), ${channels} salon(s)`,
    distribution: "Répartition",
    total: "Total",
    errors: "Erreurs",
    warns: "Alertes",
    infos: "Infos",
    debug: "Debug",
    interactions: "Interactions",
    api: "API",
    other: "Autres",
    noContext: "Aucun contexte fourni.",
    masked: "[masqué]",
    received: "Reçu",
    noLogSelected: "Aucun log sélectionné",
    access: "Accès",
    permissionDenied: "Permission refusée",
    accessChecked: "Accès vérifié",
    processing: "Traitement",
    stopOnError: "Arrêt sur erreur",
    processingDone: "Traitement terminé",
    discordCall: "Appel ou événement Discord",
    noCriticalCall: "Aucun appel critique",
    botObservatory: "Bot Observatory",
    botHealth: "Santé du bot",
    pointCheck: (count: number) => `${count} point(s) à vérifier.`,
    noActiveIncident: "Aucun incident actif.",
    back: "Retour",
    botSummary: "Résumé du bot",
    watch: "À surveiller",
    activePoints: "Points actifs",
    allWorking: "Tout fonctionne",
    logs: "Logs",
    sources: "Sources",
    activity: "Activité",
    recentEvents: "Événements récents",
    botActivityAria: "Activité du bot",
    activityTooltip: (
      total: number,
      interactions: number,
      api: number,
      errors: number,
    ) => `${interactions} interactions, ${api} API, ${errors} erreurs`,
    activityReadout: (interactions: number, api: number, errors: number) =>
      `${interactions} interaction(s), ${api} API, ${errors} erreur(s)`,
    stability: "Stabilité",
    pingGateway: "Ping gateway",
    gatewayTooltip: (gateway: number, rateLimit: number) =>
      `${gateway} log(s) gateway, ${rateLimit} rate-limit(s)`,
    latestLogs: "Derniers logs",
    usefulJournal: "Journal utile",
    noRecentLog: "Aucun log récent.",
  },
  en: {
    unknown: "Unknown",
    noActivity: "No activity",
    offline: "Offline",
    needsCheck: "Needs checking",
    operational: "Operational",
    status: "Status",
    online: "Online",
    bot: "Bot",
    gateway: "Gateway",
    eventCount: (count: number) => `${count} event(s)`,
    stable: "Stable",
    uptime: "Uptime",
    localSession: "Local session",
    servers: "Servers",
    textChannels: (count: number) => `${count} text channels`,
    commands: "Commands",
    commandsDetail: (global: number, guild: number) =>
      `${global} global, ${guild} server`,
    alerts: "Alerts",
    toHandle: "To handle",
    none: "None",
    botOfflineTitle: "Bot disconnected",
    botOfflineShort: "The bot is not receiving Discord events.",
    currentState: (state: string) => `Current state: ${state}.`,
    botOfflineFix: "Restart the connection and verify the token.",
    lastBotErrorTitle: "Last bot error",
    lastBotErrorWhy: "A Discord.js or Botdeck action recently failed.",
    lastBotErrorFix:
      "Open the related log, then fix the permission or payload.",
    lastErrorEvidence: "lastError present",
    limitedPermissionsTitle: "Limited permissions",
    limitedPermissionsShort: (count: number) => `${count} channel(s) to check.`,
    limitedPermissionsWhy:
      "The bot role or a channel permission blocks a response.",
    limitedPermissionsFix:
      "Check View Channel, Send Messages, Embed Links, and Use Application Commands.",
    payloadTitle: "Payload rejected",
    payloadShort: "Discord rejected a command, embed, modal, or identifier.",
    payloadWhy: "A field is too long, missing, or invalid.",
    payloadFix: "Read the log detail and fix the indicated field.",
    expiredTitle: "Interaction expired",
    expiredShort: "A command, button, or modal responded too late or twice.",
    expiredWhy:
      "Discord expects a quick response and only one initial response.",
    expiredFix: "Reply or defer quickly, then keep expired buttons clean.",
    rateLimitTitle: "Rate limit",
    rateLimitShort: "Discord limited an API route.",
    rateLimitWhy: "Too many calls were made too quickly.",
    rateLimitFix: "Avoid bursts and let Discord.js handle retries.",
    authTitle: "Auth or token",
    authShort: "A log mentions token, 401, 403, or unauthorized.",
    authWhy: "The token may be invalid or a global permission may be refused.",
    authFix: "Reconnect the bot and never share sensitive logs.",
    partialCommandsTitle: "Incomplete commands",
    partialCommandsWhy: "Discord did not return all expected commands.",
    partialCommandsFix: "Open Slash Studio and sync with Discord if needed.",
    partialCommandsEvidence: "partialError Slash Studio",
    allCleanTitle: "Everything is clean",
    allCleanShort: "No important blocker detected.",
    allCleanWhy:
      "The gateway is connected and recent logs show no critical error.",
    allCleanFix:
      "Continue testing. The next events will appear in the journal.",
    recentLogEvidence: (count: number) => `${count} recent log(s)`,
    logEvidence: (count: number) => `${count} log(s)`,
    permissionEvidence: (logs: number, channels: number) =>
      `${logs} log(s), ${channels} channel(s)`,
    distribution: "Distribution",
    total: "Total",
    errors: "Errors",
    warns: "Warnings",
    infos: "Info",
    debug: "Debug",
    interactions: "Interactions",
    api: "API",
    other: "Other",
    noContext: "No context provided.",
    masked: "[masked]",
    received: "Received",
    noLogSelected: "No log selected",
    access: "Access",
    permissionDenied: "Permission denied",
    accessChecked: "Access checked",
    processing: "Processing",
    stopOnError: "Stopped on error",
    processingDone: "Processing finished",
    discordCall: "Discord call or event",
    noCriticalCall: "No critical call",
    botObservatory: "Bot Observatory",
    botHealth: "Bot health",
    pointCheck: (count: number) => `${count} point(s) to check.`,
    noActiveIncident: "No active incident.",
    back: "Back",
    botSummary: "Bot summary",
    watch: "Watch",
    activePoints: "Active points",
    allWorking: "Everything works",
    logs: "Logs",
    sources: "Sources",
    activity: "Activity",
    recentEvents: "Recent events",
    botActivityAria: "Bot activity",
    activityTooltip: (
      total: number,
      interactions: number,
      api: number,
      errors: number,
    ) => `${interactions} interactions, ${api} API, ${errors} errors`,
    activityReadout: (interactions: number, api: number, errors: number) =>
      `${interactions} interaction(s), ${api} API, ${errors} error(s)`,
    stability: "Stability",
    pingGateway: "Gateway ping",
    gatewayTooltip: (gateway: number, rateLimit: number) =>
      `${gateway} gateway log(s), ${rateLimit} rate-limit(s)`,
    latestLogs: "Latest logs",
    usefulJournal: "Useful journal",
    noRecentLog: "No recent log.",
  },
} as const;

export const commandWizardText = {
  fr: {
    creationSteps: [
      "Exécution",
      "Identité",
      "Comportement",
      "Contenu",
      "Accès",
    ],
    backToCommands: "← Commandes",
    newCommand: "Nouvelle commande",
    naturalOrder: "Une question à la fois, dans l’ordre naturel.",
    serverScope: (guildName: string) => `Serveur · ${guildName}`,
    step1: "Étape 1",
    step1Title: "Comment la commande est déclenchée ?",
    step1Help:
      "On commence par l’exécution, parce que tout le reste dépend de cette forme.",
    slashCommand: "Slash command",
    slashCommandHelp: "La commande s’exécute avec /nom dans Discord.",
    userMenu: "Menu utilisateur",
    userMenuHelp: "Action disponible au clic droit sur un membre.",
    messageMenu: "Menu message",
    messageMenuHelp: "Action disponible au clic droit sur un message.",
    textPrefix: "Préfixe texte",
    textPrefixHelp: (prefix: string) =>
      `La commande s’exécute avec ${prefix || "&"}nom dans un message.`,
    step2: "Étape 2",
    step2Title: "Comment elle s’appelle ?",
    step2Help:
      "Discord demande un nom clair. Les commandes slash demandent aussi une courte description.",
    pongPlaceholder: "Répond Pong",
    contextNoDescription:
      "Les commandes User et Message n’ont pas de description publique côté Discord.",
    step3: "Étape 3",
    step3Title: "Que doit faire le bot ?",
    step3Help:
      "On choisit d’abord la forme de réponse, puis l’écran suivant s’adapte.",
    responseModes: {
      message: {
        title: "Message simple",
        description: "Le bot répond avec un texte direct.",
      },
      embed: {
        title: "Message embed",
        description: "Embed personnalisable, avec pages optionnelles.",
      },
      modal: {
        title: "Modal de recherche",
        description: "Le bot ouvre un formulaire Discord à remplir.",
      },
      welcome: {
        title: "Définir welcome",
        description: "Configure le salon de bienvenue du serveur.",
      },
      goodbye: {
        title: "Définir goodbye",
        description: "Configure le salon de départ du serveur.",
      },
      logs: {
        title: "Définir logs",
        description: "Configure le salon des logs du serveur.",
      },
      autorole: {
        title: "Role automation",
        description:
          "Liste, ajoute, supprime et synchronise les rôles automatiques.",
      },
      ban: {
        title: "Bannir",
        description: "Bannit un membre avec raison et log personnalisable.",
      },
      unban: {
        title: "Débannir",
        description: "Retire le bannissement via ID utilisateur.",
      },
      kick: {
        title: "Expulser",
        description: "Expulse un membre avec raison et log personnalisable.",
      },
    },
    step4: "Étape 4",
    contentTitle: {
      message: "Quel message envoyer ?",
      embed: "Quel embed envoyer ?",
      welcome: "Quel welcome configurer ?",
      goodbye: "Quel goodbye configurer ?",
      logs: "Quel salon logs configurer ?",
      autorole: "Quelle commande autorole créer ?",
      ban: "Quel message après ban ?",
      unban: "Quel message après unban ?",
      kick: "Quel message après expulsion ?",
      modal: "Quel formulaire ouvrir ?",
    },
    contentHelp: {
      embed:
        "L’embed peut avoir jusqu’à 10 pages. Chaque page a ses propres champs et médias.",
      welcome:
        "La commande sauvegarde un salon par serveur et enverra ce message quand un membre rejoint.",
      goodbye:
        "La commande sauvegarde un salon par serveur et enverra ce message quand un membre quitte.",
      logs: "La commande sauvegarde un salon par serveur et enverra les événements Discord dedans.",
      autorole:
        "La commande gère les règles en base, sans dépendre d'un salon.",
      moderation:
        "Personnalise la réponse de la commande. Les logs ban, unban et kick se règlent dans l’automatisation logs.",
      default: "On configure seulement ce qui sera réellement utilisé.",
    },
    commandAutorole: "Commande /autorole",
    autoroleActions: "Actions autorole",
    autoroleModeHelp:
      "Options créées: action, role, id, messages, vocal_min, anciennete_jours et mode. Le bot doit avoir Manage Roles et son rôle doit être au-dessus des rôles à attribuer.",
  },
  en: {
    creationSteps: ["Execution", "Identity", "Behavior", "Content", "Access"],
    backToCommands: "← Commands",
    newCommand: "New command",
    naturalOrder: "One question at a time, in the natural order.",
    serverScope: (guildName: string) => `Server · ${guildName}`,
    step1: "Step 1",
    step1Title: "How is the command triggered?",
    step1Help:
      "Start with execution, because everything else depends on that shape.",
    slashCommand: "Slash command",
    slashCommandHelp: "The command runs with /name in Discord.",
    userMenu: "User menu",
    userMenuHelp: "Action available by right-clicking a member.",
    messageMenu: "Message menu",
    messageMenuHelp: "Action available by right-clicking a message.",
    textPrefix: "Text prefix",
    textPrefixHelp: (prefix: string) =>
      `The command runs with ${prefix || "&"}name in a message.`,
    step2: "Step 2",
    step2Title: "What is it called?",
    step2Help:
      "Discord requires a clear name. Slash commands also need a short description.",
    pongPlaceholder: "Reply Pong",
    contextNoDescription:
      "User and Message commands do not have a public Discord description.",
    step3: "Step 3",
    step3Title: "What should the bot do?",
    step3Help: "Choose the response shape first, then the next screen adapts.",
    responseModes: {
      message: {
        title: "Simple message",
        description: "The bot replies with direct text.",
      },
      embed: {
        title: "Embed message",
        description: "Customizable embed with optional pages.",
      },
      modal: {
        title: "Search modal",
        description: "The bot opens a Discord form to fill in.",
      },
      welcome: {
        title: "Set welcome",
        description: "Configure the server welcome channel.",
      },
      goodbye: {
        title: "Set goodbye",
        description: "Configure the server goodbye channel.",
      },
      logs: {
        title: "Set logs",
        description: "Configure the server logs channel.",
      },
      autorole: {
        title: "Role automation",
        description: "List, add, remove, and sync automatic roles.",
      },
      ban: {
        title: "Ban",
        description: "Ban a member with custom reason and log.",
      },
      unban: { title: "Unban", description: "Remove a ban using a user ID." },
      kick: {
        title: "Kick",
        description: "Kick a member with custom reason and log.",
      },
    },
    step4: "Step 4",
    contentTitle: {
      message: "Which message should be sent?",
      embed: "Which embed should be sent?",
      welcome: "Which welcome should be configured?",
      goodbye: "Which goodbye should be configured?",
      logs: "Which logs channel should be configured?",
      autorole: "Which autorole command should be created?",
      ban: "Which ban response?",
      unban: "Which unban response?",
      kick: "Which kick response?",
      modal: "Which form should open?",
    },
    contentHelp: {
      embed:
        "The embed can have up to 10 pages. Each page has its own fields and media.",
      welcome:
        "The command saves one channel per server and sends this message when a member joins.",
      goodbye:
        "The command saves one channel per server and sends this message when a member leaves.",
      logs: "The command saves one channel per server and sends Discord events there.",
      autorole:
        "The command manages database rules without depending on a channel.",
      moderation:
        "Customize the command response. Ban, unban, and kick logs are configured in logs automation.",
      default: "Only what will actually be used is configured.",
    },
    commandAutorole: "Command /autorole",
    autoroleActions: "Autorole actions",
    autoroleModeHelp:
      "Created options: action, role, id, messages, vocal_min, anciennete_jours, and mode. The bot needs Manage Roles and its role must be above the roles it assigns.",
  },
} as const;

export function wizardLabels(text: UiText) {
  return text === uiText.en ? commandWizardText.en : commandWizardText.fr;
}

// Libellés Slash Studio.
export function slashLabels(text: UiText) {
  return text === uiText.en ? slashStudioText.en : slashStudioText.fr;
}

