// Libellés des paramètres serveur

import { type UiText, uiText } from "@/features/workspace/core";

export const serverSettingsText = {
	fr: {
		serverAutomationEyebrow: "Automatisation serveur",
		serverSettingsTitle: "Paramètres du serveur",
		serverSettingsSections: "Sections des paramètres serveur",
		overviewTab: "Infos serveur",
		membersTab: "Membres",
		invitesTab: "Invitations",
		automationsTab: "Automatisations",
		templatesTab: "Modèles",
		overviewSummary: "Résumé",
		overviewSummaryHelp: "Les informations utiles du serveur courant.",
		members: "Membres",
		knownMembers: (count: number | string) => `${count} membres connus par BotDeck.`,
		serverMembersTitle: "Membres du serveur",
		serverMembersHelp: "Consulte la liste complète des membres connus du serveur.",
		membersSearchLabel: "Rechercher un membre",
		membersSearchPlaceholder: "Nom, pseudo, ID utilisateur ou rôle...",
		membersResultSummary: (visible: number, total: number) => `${visible} sur ${total} membres`,
		membersPageStatus: (page: number, total: number) => `Page ${page} sur ${total}`,
		membersEmpty: "Aucun membre chargé. Ouvre cet onglet quand le bot est connecté pour lancer la synchronisation.",
		membersNoResults: "Aucun membre ne correspond à cette recherche.",
		membersPreviousPage: "Page précédente",
		membersNextPage: "Page suivante",
		memberBotBadge: "APP",
		memberUserBadge: "Utilisateur",
		memberColumnName: "Membre",
		memberColumnUsername: "Pseudo",
		memberJoinedAt: "Arrivé",
		memberRoles: "Rôles",
		memberNoRoles: "Aucun rôle",
		memberMoreRoles: (count: number) => `+${count} autre${count > 1 ? "s" : ""}`,
		memberId: "ID utilisateur",
		membersSortInactive: "Cliquer pour trier",
		membersSortAscending: "Tri croissant",
		membersSortDescending: "Tri décroissant",
		memberAddRole: "Ajouter un rôle",
		memberNoRoleToAdd: "Aucun rôle disponible à ajouter.",
		memberManagedRole: "Rôle géré par une intégration.",
		memberRemoveRole: (role: string) => `Retirer le rôle ${role}`,
		memberRoleAdding: (role: string, member: string) => `Ajout du rôle ${role} à ${member}.`,
		memberRoleRemoving: (role: string, member: string) => `Retrait du rôle ${role} de ${member}.`,
		serverInvitesTitle: "Invitations du serveur",
		serverInvitesHelp: "Consulte et gère les invitations actives du serveur.",
		invitesSearchLabel: "Rechercher une invitation",
		invitesSearchPlaceholder: "Code, salon, créateur...",
		invitesResultSummary: (visible: number, total: number) => `${visible} sur ${total} invitations`,
		invitesPageStatus: (page: number, total: number) => `Page ${page} sur ${total}`,
		invitesEmpty: "Aucune invitation chargée. Ouvre cet onglet quand le bot est connecté pour lancer la synchronisation.",
		invitesNoResults: "Aucune invitation ne correspond à cette recherche.",
		invitesPreviousPage: "Page précédente",
		invitesNextPage: "Page suivante",
		inviteCode: "Code",
		inviteChannel: "Salon",
		inviteCreator: "Créateur",
		inviteUses: "Utilisations",
		inviteExpires: "Expiration",
		inviteActions: "Actions",
		inviteNeverExpires: "Jamais",
		inviteUnlimited: "Illimité",
		inviteTemporary: "Temporaire",
		invitePermanent: "Permanent",
		inviteCopy: "Copier le lien",
		inviteCopied: "Lien d'invitation copié.",
		inviteDelete: "Supprimer l'invitation",
		inviteDeleting: (code: string) => `Suppression de l'invitation ${code}.`,
		inviteCreate: "Créer une invitation",
		inviteCreateDialog: "Nouvelle invitation",
		inviteCreateHelp: "Choisis un salon et les limites de l'invitation.",
		inviteChannelToUse: "Salon de destination",
		inviteExpiration: "Durée de validité",
		inviteMaxUses: "Nombre maximal d'utilisations",
		inviteTemporaryMembership: "Membre temporaire",
		inviteUnique: "Créer un lien unique",
		inviteDuration30m: "30 minutes",
		inviteDuration1h: "1 heure",
		inviteDuration6h: "6 heures",
		inviteDuration12h: "12 heures",
		inviteDuration1d: "1 jour",
		inviteDuration7d: "7 jours",
		inviteDurationNever: "Jamais",
		inviteMaxUsesNone: "Illimité",
		inviteMaxUsesOne: "1 utilisation",
		inviteMaxUsesFive: "5 utilisations",
		inviteMaxUsesTen: "10 utilisations",
		inviteMaxUsesTwentyFive: "25 utilisations",
		inviteMaxUsesFifty: "50 utilisations",
		inviteMaxUsesHundred: "100 utilisations",
		inviteCreating: "Création de l'invitation serveur.",
		inviteSelectChannelBeforeCreate: "Sélectionne un salon avant de créer l'invitation.",
		inviteNoChannelAvailable: "Aucun salon compatible disponible.",
		bansTab: "Bannissements",
		serverBansTitle: "Bannissements du serveur",
		serverBansHelp: "Consulte les utilisateurs bannis et débannis-les si nécessaire.",
		bansSearchLabel: "Rechercher un bannissement",
		bansSearchPlaceholder: "Nom, ID utilisateur ou raison...",
		bansResultSummary: (visible: number, total: number) => `${visible} sur ${total} bannissements`,
		bansEmpty: "Aucun bannissement chargé.",
		bansNoResults: "Aucun bannissement ne correspond à cette recherche.",
		banUserId: "ID utilisateur",
		banReason: "Raison",
		banCreate: "Bannir par ID",
		banCreateDialog: "Nouveau bannissement",
		banCreateHelp: "Entre l'ID Discord de l'utilisateur à bannir. La raison est optionnelle.",
		banUserIdPlaceholder: "ID utilisateur Discord",
		banReasonPlaceholder: "Raison optionnelle",
		banCreating: "Création du bannissement serveur.",
		banDeleting: (user: string) => `Débannissement de ${user}.`,
		unban: "Débannir",
		serverChannels: "Salons",
		channelSummary: (textCount: number, voiceCount: number, forumCount: number, categoryCount: number) => `${textCount} textuels, ${voiceCount} vocaux, ${forumCount} forums, ${categoryCount} catégories.`,
		identity: "Identité",
		identityHelp: "Données techniques utiles pour relier le serveur aux réglages Botdeck.",
		serverId: "ID serveur",
		owner: "Propriétaire",
		notLoaded: "Non chargé",
		activeBot: "Bot actif",
		connectedWorkspace: "Connecté à ce workspace.",
		noActiveBot: "Aucun bot actif.",
		connected: "Connecté",
		active: "Actif",
		inactive: "Inactif",
		readOnlyModeTitle: "Mode lecture seule actif",
		readOnlyModeHelp: "Ce bot est marqué comme géré ailleurs. Les modèles et automatisations serveur sont consultables seulement, car cette protection est obligatoire en mode lecture seule.",
		readOnlyModeActionBlocked: "Mode lecture seule actif : modèles et automatisations serveur non modifiables.",
		readOnlyModeTooltip: "Ce bot est en lecture seule.",
		serverAutomationsTitle: "Automatisations serveur",
		serverAutomationsHelp: "Définis uniquement les salons et teste les automatismes. Les messages se règlent dans Modèles.",
		welcomeChannelTitle: "Salon de bienvenue",
		welcomeChannelDescription: "Envoyé quand un membre rejoint.",
		goodbyeChannelTitle: "Salon de goodbye",
		goodbyeChannelDescription: "Envoyé quand un membre quitte.",
		logsChannelTitle: "Salon de logs",
		logsChannelDescription: "Messages de logs envoyés dans un salon par défaut.",
		selectChannelSr: "Salon",
		selectChannelPlaceholder: "Salon à sélectionner",
		testAutomation: (title: string) => `Tester ${title}`,
		editAutomation: (title: string) => `Modifier ${title}`,
		saveFirstAutomation: "Enregistre d'abord cette automatisation",
		testLogs: "Tester les logs",
		editLogs: "Modifier les logs",
		roleAutomationTitle: "Rôles automatiques",
		roleAutomationDescription: "Attribue un rôle selon l'arrivée, les messages, le vocal ou l'ancienneté.",
		activeCount: (count: number) => `${count} actif${count > 1 ? "s" : ""}`,
		add: "Ajouter",
		sync: "Synchroniser",
		testRoleAutomation: "Tester les rôles automatiques",
		editRule: "Modifier la règle",
		deleteRule: "Supprimer la règle",
		noRole: "Aucun rôle",
		roleIdFallback: (id: string) => `Rôle ${id.slice(-6)}`,
		oneConditionEnough: "une condition suffit",
		allConditionsRequired: "toutes les conditions",
		messagesCondition: (count: string) => `${count} messages`,
		voiceCondition: (minutes: string) => `${minutes} min vocal`,
		memberAgeCondition: (days: string) => `${days} j serveur`,
		conditionJoin: "À l'arrivée",
		conditionOr: " ou ",
		conditionAnd: " + ",
		noRoleRule: "Aucune règle. Ajoute un rôle donné à l'arrivée ou selon activité.",
		roleAutomationDialog: "Rôle automatique",
		roleAutomationHelp: "Définis le rôle et les conditions nécessaires.",
		roleToAssign: "Rôle à attribuer",
		selectRolePlaceholder: "Rôle à sélectionner",
		mode: "Mode",
		allConditions: "Toutes les conditions",
		anyCondition: "Une seule condition",
		requiredMessages: "Messages requis",
		requiredVoiceMinutes: "Vocal requis en minutes",
		memberAgeDays: "Ancienneté en jours",
		disabledZero: "0 = désactivé",
		joinZero: "0 = à l'arrivée",
		ruleEnabled: "Règle active",
		applyExistingMembers: "Appliquer aussi aux membres existants",
		ignoreBots: "Ignorer les bots",
		removeWhenInvalid: "Retirer le rôle si les conditions ne sont plus valides",
		roleAutomationNote: "Sans condition, le rôle est donné à l'arrivée. Le temps vocal est compté par BotDeck avec les événements vocaux à partir de l'activation.",
		templatesTitle: "Modèles serveur",
		templatesHelp: "Centralise tous les messages configurables du serveur.",
		templatesAutoMessages: "Messages automatiques",
		templatesAutoMessagesHelp: "Ces modèles sont utilisés par les salons de bienvenue et de départ.",
		templatesLogMessages: "Modèles de logs",
		templatesLogMessagesHelp: "Un modèle par événement : ban, unban, kick, purge, salons, messages.",
		templatesAllMessages: "Tous les messages",
		templatesAllMessagesHelp: "Liste compacte des messages configurables. Recherche, sélection, puis édition à droite.",
		templatesSearch: "Recherche",
		templatesSearchPlaceholder: "Bienvenue, salon, ban, purge...",
		templatesNoResults: "Aucun message trouvé.",
		templatesEnableLog: "Activer ce log",
		templatesDisableLog: "Désactiver ce log",
		templatesWelcomeDescription: "Message envoyé quand un membre rejoint le serveur.",
		templatesGoodbyeDescription: "Message envoyé quand un membre quitte le serveur.",
		templatesMessageLogDescription: "Message envoyé dans les logs pour un événement lié aux messages.",
		templatesChannelLogDescription: "Message envoyé dans les logs pour un événement lié aux salons.",
		templatesModerationLogDescription: "Message envoyé dans les logs pour une action de modération.",
		templatesPurgeDescription: "Message envoyé dans les logs après une purge par recréation.",
		templatesTagWelcome: "Bienvenue",
		templatesTagGoodbye: "Départ",
		templatesTagLogs: "Logs",
		templatesTagMessages: "Messages",
		templatesTagChannels: "Salons",
		templatesTagModeration: "Modération",
		templatesTagPurge: "Purge",
		templatesSaveHint: "Enregistre les modifications avec la barre en bas du panneau.",
		templatesTemplateActions: "Actions du modèle sélectionné",
		templatesImportTemplate: "Importer ce modèle",
		templatesExportTemplate: "Exporter ce modèle",
		templatesImportInvalidPackage: "Package Botdeck invalide.",
		templatesImportNoTemplates: "Ce package ne contient aucun modèle.",
		templatesImportNoCompatibleTemplate: "Aucun modèle compatible avec le modèle sélectionné.",
		templatesImportConfirmAll: (count: number) => `Importer ${count} modèles localement ? Rien ne sera activé automatiquement.`,
		templatesImportSuccess: (count: number) => `${count} modèle${count > 1 ? "s" : ""} importé${count > 1 ? "s" : ""} localement.`,
		templatesImportSingleSuccess: "Modèle importé localement.",
		templatesImportError: "Impossible d'importer les modèles.",
		templatesWelcomeExportName: "Modèle de bienvenue",
		templatesGoodbyeExportName: "Modèle de départ",
		templatesLogExportName: (title: string) => `Modèle de log ${title}`,
		templatesPackName: "Pack de modèles Botdeck",
		customizeLogEvents: "Personnalise chaque événement envoyé dans le salon de logs.",
		customizeAutoMessage: "Personnalise le message public envoyé automatiquement.",
		messageFormat: "Format du message",
		simpleMessage: "Message simple",
		embed: "Embed",
		welcomeMessage: "Message de bienvenue",
		goodbyeMessage: "Message de départ",
		logEvents: "Événements de logs",
		logStateFormat: "État et format du log",
		message: "Message",
		logEventText: "Texte de l'événement",
		usefulVariables: "Variables utiles",
		fallbackWelcomeTitle: "Bienvenue sur {guild.name}",
		fallbackGoodbyeTitle: "Départ de {guild.name}",
		defineLogsBeforeSave: "Définis un salon de logs avant d'enregistrer.",
		defineChannelBeforeSave: (kind: string) => `Définis un salon ${kind} avant d'enregistrer.`,
		logsSaving: "Automatisation logs en cours d'enregistrement.",
		templatesSaving: "Modèles enregistrés.",
		automationSaving: (kind: string) => `Automatisation ${kind} en cours d'enregistrement.`,
		roleAutomationSaving: "Rôles automatiques en cours d'enregistrement.",
		testRunning: (kind: string) => `Test ${kind} en cours.`,
		roleAutomationSyncing: "Synchronisation des rôles automatiques en cours.",
		roleAutomationTesting: "Test des rôles automatiques en cours.",
		welcomeKind: "welcome",
		goodbyeKind: "goodbye",
		logsKind: "logs",
		logEventLabels: {
			message_edit: "Message modifié",
			message_delete: "Message supprimé",
			channel_create: "Salon créé",
			channel_update: "Salon modifié",
			channel_delete: "Salon supprimé",
			channel_recreate_purge: "Salon réinitialisé",
			member_ban: "Membre banni",
			member_unban: "Membre débanni",
			member_kick: "Membre expulsé"
		}
	},
	en: {
		serverAutomationEyebrow: "Server automation",
		serverSettingsTitle: "Server settings",
		serverSettingsSections: "Server settings sections",
		overviewTab: "Server info",
		membersTab: "Members",
		invitesTab: "Invites",
		automationsTab: "Automations",
		templatesTab: "Templates",
		overviewSummary: "Summary",
		overviewSummaryHelp: "Useful information for the current server.",
		members: "Members",
		knownMembers: (count: number | string) => `${count} members known by BotDeck.`,
		serverMembersTitle: "Server members",
		serverMembersHelp: "Browse the complete list of known server members.",
		membersSearchLabel: "Search a member",
		membersSearchPlaceholder: "Name, username, user ID, or role...",
		membersResultSummary: (visible: number, total: number) => `${visible} of ${total} members`,
		membersPageStatus: (page: number, total: number) => `Page ${page} of ${total}`,
		membersEmpty: "No members loaded yet. Open this tab while the bot is connected to start synchronization.",
		membersNoResults: "No member matches this search.",
		membersPreviousPage: "Previous page",
		membersNextPage: "Next page",
		memberBotBadge: "APP",
		memberUserBadge: "User",
		memberColumnName: "Member",
		memberColumnUsername: "Username",
		memberJoinedAt: "Joined",
		memberRoles: "Roles",
		memberNoRoles: "No roles",
		memberMoreRoles: (count: number) => `+${count} more`,
		memberId: "User ID",
		membersSortInactive: "Click to sort",
		membersSortAscending: "Sorted ascending",
		membersSortDescending: "Sorted descending",
		memberAddRole: "Add a role",
		memberNoRoleToAdd: "No role available to add.",
		memberManagedRole: "Role managed by an integration.",
		memberRemoveRole: (role: string) => `Remove ${role} role`,
		memberRoleAdding: (role: string, member: string) => `Adding ${role} to ${member}.`,
		memberRoleRemoving: (role: string, member: string) => `Removing ${role} from ${member}.`,
		serverInvitesTitle: "Server invites",
		serverInvitesHelp: "Browse and manage active server invites.",
		invitesSearchLabel: "Search an invite",
		invitesSearchPlaceholder: "Code, channel, creator...",
		invitesResultSummary: (visible: number, total: number) => `${visible} of ${total} invites`,
		invitesPageStatus: (page: number, total: number) => `Page ${page} of ${total}`,
		invitesEmpty: "No invites loaded yet. Open this tab while the bot is connected to start synchronization.",
		invitesNoResults: "No invite matches this search.",
		invitesPreviousPage: "Previous page",
		invitesNextPage: "Next page",
		inviteCode: "Code",
		inviteChannel: "Channel",
		inviteCreator: "Creator",
		inviteUses: "Uses",
		inviteExpires: "Expires",
		inviteActions: "Actions",
		inviteNeverExpires: "Never",
		inviteUnlimited: "Unlimited",
		inviteTemporary: "Temporary",
		invitePermanent: "Permanent",
		inviteCopy: "Copy link",
		inviteCopied: "Invite link copied.",
		inviteDelete: "Delete invite",
		inviteDeleting: (code: string) => `Deleting invite ${code}.`,
		inviteCreate: "Create invite",
		inviteCreateDialog: "New invite",
		inviteCreateHelp: "Choose a channel and invite limits.",
		inviteChannelToUse: "Destination channel",
		inviteExpiration: "Expiration",
		inviteMaxUses: "Maximum uses",
		inviteTemporaryMembership: "Temporary membership",
		inviteUnique: "Create a unique link",
		inviteDuration30m: "30 minutes",
		inviteDuration1h: "1 hour",
		inviteDuration6h: "6 hours",
		inviteDuration12h: "12 hours",
		inviteDuration1d: "1 day",
		inviteDuration7d: "7 days",
		inviteDurationNever: "Never",
		inviteMaxUsesNone: "Unlimited",
		inviteMaxUsesOne: "1 use",
		inviteMaxUsesFive: "5 uses",
		inviteMaxUsesTen: "10 uses",
		inviteMaxUsesTwentyFive: "25 uses",
		inviteMaxUsesFifty: "50 uses",
		inviteMaxUsesHundred: "100 uses",
		inviteCreating: "Creating server invite.",
		inviteSelectChannelBeforeCreate: "Select a channel before creating the invite.",
		inviteNoChannelAvailable: "No compatible channel available.",
		bansTab: "Bans",
		serverBansTitle: "Server bans",
		serverBansHelp: "Browse banned users and unban them when needed.",
		bansSearchLabel: "Search a ban",
		bansSearchPlaceholder: "Name, user ID, or reason...",
		bansResultSummary: (visible: number, total: number) => `${visible} of ${total} bans`,
		bansEmpty: "No bans loaded yet.",
		bansNoResults: "No ban matches this search.",
		banUserId: "User ID",
		banReason: "Reason",
		banCreate: "Ban by ID",
		banCreateDialog: "New ban",
		banCreateHelp: "Enter the Discord user ID to ban. The reason is optional.",
		banUserIdPlaceholder: "Discord user ID",
		banReasonPlaceholder: "Optional reason",
		banCreating: "Creating server ban.",
		banDeleting: (user: string) => `Unbanning ${user}.`,
		unban: "Unban",
		serverChannels: "Channels",
		channelSummary: (textCount: number, voiceCount: number, forumCount: number, categoryCount: number) => `${textCount} text, ${voiceCount} voice, ${forumCount} forum, ${categoryCount} categories.`,
		identity: "Identity",
		identityHelp: "Technical data used to connect this server to Botdeck settings.",
		serverId: "Server ID",
		owner: "Owner",
		notLoaded: "Not loaded",
		activeBot: "Active bot",
		connectedWorkspace: "Connected to this workspace.",
		noActiveBot: "No active bot.",
		connected: "Connected",
		active: "Active",
		inactive: "Inactive",
		readOnlyModeTitle: "Read-only mode active",
		readOnlyModeHelp: "This bot is marked as managed elsewhere. Server templates and automations are view-only because this protection is required in read-only mode.",
		readOnlyModeActionBlocked: "Read-only mode active: server templates and automations cannot be changed.",
		readOnlyModeTooltip: "This bot is read-only.",
		serverAutomationsTitle: "Server automations",
		serverAutomationsHelp: "Only define channels and test automations here. Messages are configured in Templates.",
		welcomeChannelTitle: "Welcome channel",
		welcomeChannelDescription: "Sent when a member joins.",
		goodbyeChannelTitle: "Goodbye channel",
		goodbyeChannelDescription: "Sent when a member leaves.",
		logsChannelTitle: "Logs channel",
		logsChannelDescription: "Log messages sent to a default channel.",
		selectChannelSr: "Channel",
		selectChannelPlaceholder: "Select a channel",
		testAutomation: (title: string) => `Test ${title}`,
		editAutomation: (title: string) => `Edit ${title}`,
		saveFirstAutomation: "Save this automation first",
		testLogs: "Test logs",
		editLogs: "Edit logs",
		roleAutomationTitle: "Automatic roles",
		roleAutomationDescription: "Assign a role based on join, messages, voice, or membership age.",
		activeCount: (count: number) => `${count} active`,
		add: "Add",
		sync: "Sync",
		testRoleAutomation: "Test automatic roles",
		editRule: "Edit rule",
		deleteRule: "Delete rule",
		noRole: "No role",
		roleIdFallback: (id: string) => `Role ${id.slice(-6)}`,
		oneConditionEnough: "one condition is enough",
		allConditionsRequired: "all conditions required",
		messagesCondition: (count: string) => `${count} messages`,
		voiceCondition: (minutes: string) => `${minutes} voice min`,
		memberAgeCondition: (days: string) => `${days} server days`,
		conditionJoin: "On join",
		conditionOr: " or ",
		conditionAnd: " + ",
		noRoleRule: "No rule yet. Add an on-join role or an activity-based role.",
		roleAutomationDialog: "Automatic role",
		roleAutomationHelp: "Define the role and required conditions.",
		roleToAssign: "Role to assign",
		selectRolePlaceholder: "Select a role",
		mode: "Mode",
		allConditions: "All conditions",
		anyCondition: "Any condition",
		requiredMessages: "Required messages",
		requiredVoiceMinutes: "Required voice minutes",
		memberAgeDays: "Membership age in days",
		disabledZero: "0 = disabled",
		joinZero: "0 = on join",
		ruleEnabled: "Rule enabled",
		applyExistingMembers: "Also apply to existing members",
		ignoreBots: "Ignore bots",
		removeWhenInvalid: "Remove the role when conditions are no longer valid",
		roleAutomationNote: "Without a condition, the role is given on join. Voice time is counted by BotDeck from voice events after activation.",
		templatesTitle: "Server templates",
		templatesHelp: "Centralize every configurable server message.",
		templatesAutoMessages: "Automatic messages",
		templatesAutoMessagesHelp: "These templates are used by the welcome and goodbye channels.",
		templatesLogMessages: "Log templates",
		templatesLogMessagesHelp: "One template per event: ban, unban, kick, purge, channels and messages.",
		templatesAllMessages: "All messages",
		templatesAllMessagesHelp: "Compact list of configurable messages. Search, select, then edit on the right.",
		templatesSearch: "Search",
		templatesSearchPlaceholder: "Welcome, channel, ban, purge...",
		templatesNoResults: "No message found.",
		templatesEnableLog: "Enable this log",
		templatesDisableLog: "Disable this log",
		templatesWelcomeDescription: "Message sent when a member joins the server.",
		templatesGoodbyeDescription: "Message sent when a member leaves the server.",
		templatesMessageLogDescription: "Message sent to logs for a message-related event.",
		templatesChannelLogDescription: "Message sent to logs for a channel-related event.",
		templatesModerationLogDescription: "Message sent to logs for a moderation action.",
		templatesPurgeDescription: "Message sent to logs after a recreate purge.",
		templatesTagWelcome: "Welcome",
		templatesTagGoodbye: "Goodbye",
		templatesTagLogs: "Logs",
		templatesTagMessages: "Messages",
		templatesTagChannels: "Channels",
		templatesTagModeration: "Moderation",
		templatesTagPurge: "Purge",
		templatesSaveHint: "Save changes with the bar at the bottom of the panel.",
		templatesTemplateActions: "Selected template actions",
		templatesImportTemplate: "Import this template",
		templatesExportTemplate: "Export this template",
		templatesImportInvalidPackage: "Invalid Botdeck package.",
		templatesImportNoTemplates: "This package does not contain templates.",
		templatesImportNoCompatibleTemplate: "No compatible template found for the selected template.",
		templatesImportConfirmAll: (count: number) => `Import ${count} templates locally? Nothing will be enabled automatically.`,
		templatesImportSuccess: (count: number) => `${count} template${count > 1 ? "s" : ""} imported locally.`,
		templatesImportSingleSuccess: "Template imported locally.",
		templatesImportError: "Could not import templates.",
		templatesWelcomeExportName: "Welcome template",
		templatesGoodbyeExportName: "Goodbye template",
		templatesLogExportName: (title: string) => `${title} log template`,
		templatesPackName: "Botdeck template pack",
		customizeLogEvents: "Customize each event sent to the logs channel.",
		customizeAutoMessage: "Customize the public message sent automatically.",
		messageFormat: "Message format",
		simpleMessage: "Simple message",
		embed: "Embed",
		welcomeMessage: "Welcome message",
		goodbyeMessage: "Goodbye message",
		logEvents: "Log events",
		logStateFormat: "Log state and format",
		message: "Message",
		logEventText: "Event text",
		usefulVariables: "Useful variables",
		fallbackWelcomeTitle: "Welcome to {guild.name}",
		fallbackGoodbyeTitle: "Left {guild.name}",
		defineLogsBeforeSave: "Define a logs channel before saving.",
		defineChannelBeforeSave: (kind: string) => `Define a ${kind} channel before saving.`,
		logsSaving: "Logs automation is being saved.",
		templatesSaving: "Templates saved.",
		automationSaving: (kind: string) => `${kind} automation is being saved.`,
		roleAutomationSaving: "Automatic roles are being saved.",
		testRunning: (kind: string) => `${kind} test is running.`,
		roleAutomationSyncing: "Automatic role sync is running.",
		roleAutomationTesting: "Automatic role test is running.",
		welcomeKind: "welcome",
		goodbyeKind: "goodbye",
		logsKind: "logs",
		logEventLabels: {
			message_edit: "Message edited",
			message_delete: "Message deleted",
			channel_create: "Channel created",
			channel_update: "Channel updated",
			channel_delete: "Channel deleted",
			channel_recreate_purge: "Channel reset",
			member_ban: "Member banned",
			member_unban: "Member unbanned",
			member_kick: "Member kicked"
		}
	}
} as const;

export type ServerSettingsText = (typeof serverSettingsText)[keyof typeof serverSettingsText];

export function serverLabels(text: UiText): ServerSettingsText {
	return text === uiText.en ? serverSettingsText.en : serverSettingsText.fr;
}

